import 'package:pos_app/app_settings/app_settings_model.dart';

/// Data extracted from a weighing-scale barcode.
class ParsedScaleData {
  final String productCode;
  final double parsedValue;

  /// true  → parsedValue is a price; quantity = parsedValue / product.price
  /// false → parsedValue is a weight/quantity; use it directly
  final bool isPrice;

  const ParsedScaleData({
    required this.productCode,
    required this.parsedValue,
    required this.isPrice,
  });
}

/// Attempts to decode [barcode] as a scale-printed barcode.
///
/// Format assumed:
///   [prefix][codeLength digits][value digits][1 control/check digit]
///
/// The value segment's width is *derived* from the barcode (everything between
/// the product code and the final single control digit) rather than hard-coded,
/// so any prefix / product-code-length combination decodes correctly.
///
/// Example (prefix "20", codeLength 5, decimalPlaces 3):
///   "20" + "10001" + "00350" + "2"  →  code "10001", value 0.350
///
/// Returns null when:
/// • [Scale.Barcode.Enabled] is not 'true'
/// • The barcode does not start with the configured prefix
/// • The barcode body is shorter than codeLength + 2 characters
///   (need at least one value digit and the control digit)
/// • The value segment is not numeric
ParsedScaleData? parseScaleBarcode(
  String barcode,
  Map<String, String> settings,
) {
  if (settings[SettingKeys.scaleBarcodeEnabled]?.toLowerCase() != 'true') {
    return null;
  }

  final prefix = settings[SettingKeys.scaleBarcodePrefix] ?? '';
  if (prefix.isNotEmpty && !barcode.startsWith(prefix)) return null;

  final body = barcode.substring(prefix.length);

  final codeLen =
      (int.tryParse(settings[SettingKeys.scaleBarcodeCodeLength] ?? '5') ?? 5)
          .clamp(1, 20);
  final decPlaces =
      (int.tryParse(
                settings[SettingKeys.scaleBarcodeDecimalPlaces] ?? '3',
              ) ??
              3)
          .clamp(0, 5);
  final trimZeros =
      settings[SettingKeys.scaleBarcodeTrimZeros]?.toLowerCase() != 'false';
  final isPrice =
      settings[SettingKeys.scaleBarcodePrintsPrice]?.toLowerCase() == 'true';

  // Need at least: codeLen product digits + 1 value digit + 1 control digit.
  if (body.length < codeLen + 2) return null;

  // Extract and optionally trim the product code.
  String productCode = body.substring(0, codeLen);
  if (trimZeros) productCode = productCode.replaceAll(RegExp(r'^0+'), '');
  if (productCode.isEmpty) return null;

  // The value is everything between the product code and the final single
  // control/check digit (auto-generated by the scale). Deriving its width from
  // the barcode — instead of assuming 5 digits — keeps decoding correct for any
  // prefix / code-length combination.
  final valueStr = body.substring(codeLen, body.length - 1);
  final rawValue = int.tryParse(valueStr);
  if (rawValue == null) return null;

  final parsedValue = rawValue / _pow10(decPlaces);

  return ParsedScaleData(
    productCode: productCode,
    parsedValue: parsedValue,
    isPrice: isPrice,
  );
}

int _pow10(int exp) {
  var r = 1;
  for (var i = 0; i < exp; i++) {
    r *= 10;
  }
  return r;
}
